services:
  ohmnanon-site:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # 持久化数据库文件
      - ./data:/app/data
      # 持久化上传文件
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: ohmnanon-cp-site

volumes:
  data:
